name: Build and Run Cloud DNS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      node_id:
        description: 'Node ID'
        required: false
        default: ''
      secret:
        description: 'Secret'
        required: false
        default: ''
      rpc_endpoints:
        description: 'RPC Endpoints'
        required: false
        default: 'http://127.0.0.1:8003'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: cloud-dns:latest
        
    - name: Run Docker container
      env:
        NODE_ID: ${{ github.event.inputs.node_id || '' }}
        SECRET: ${{ github.event.inputs.secret || '' }}
        RPC_ENDPOINTS: ${{ github.event.inputs.rpc_endpoints || 'http://127.0.0.1:8003' }}
      run: |
        docker run -d \
          -e NODE_ID="${NODE_ID}" \
          -e SECRET="${SECRET}" \
          -e RPC_ENDPOINTS="${RPC_ENDPOINTS}" \
          --name cloud-dns-container \
          -p 53:53 \
          -p 8003:8003 \
          cloud-dns:latest
          
    - name: Check container logs
      run: |
        sleep 5
        docker logs cloud-dns-container
        
    - name: Verify container is running
      run: |
        if [ "$(docker inspect -f '{{.State.Running}}' cloud-dns-container)" = "true" ]; then
          echo "Container is running successfully"
        else
          echo "Container failed to start"
          docker logs cloud-dns-container
          exit 1
        fi
